apiVersion: apps/v1
kind: Deployment
metadata:
  name: followers-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: followers
  template:
    metadata:
      labels:
        app: followers
    spec:
      containers:
        - name: followers
          image: rsoteam8/followers:1.0.0-SNAPSHOT-13.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 20
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: followers
spec:
  type: ClusterIP
  ports:
    - port: 8084
      protocol: TCP
      targetPort: server
  selector:
    app: followers

